# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2ff65ea967dae759c34b8748830d13e8d17b773a3f74a5dd9a68543dc53fd9dd2b90e289c23d56ffccc09ccc378044257fc9527727624ec18a1806f790469b8

test:
  secret_key_base: 91f31fa49d0c147fb11ef9aa7466c062563db4a997631613608dd13307611138b172928fd87a40bcf36d0440440472c9c301b0516fa2db478890826a9d3f041d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
